-- version 0.6.2

-- archive line item

CREATE OR REPLACE FUNCTION archive_line_item(
    p_order_line_item_id INT,
    p_jcn VARCHAR,
    p_twcode VARCHAR,
    p_nomenclature TEXT,
    p_cog VARCHAR,
    p_fsc VARCHAR,
    p_niin VARCHAR,
    p_part_no VARCHAR,
    p_qty INT,
    p_ui VARCHAR,
    p_market_research_up MONEY,
    p_market_research_ep MONEY,
    p_avail_typ VARCHAR,
    p_request_date DATE,
    p_rdd DATE,
    p_pri VARCHAR,
    p_swlin VARCHAR,
    p_hull_or_shop VARCHAR,
    p_suggested_source TEXT,
    p_mfg_cage VARCHAR,
    p_apl VARCHAR,
    p_nha_equipment_system TEXT,
    p_nha_model TEXT,
    p_nha_serial TEXT,
    p_techmanual TEXT,
    p_dwg_pc TEXT,
    p_requestor_remarks TEXT,
    p_inquiry_status BOOLEAN,
    p_created_by INT,
    p_created_at TIMESTAMPTZ,
    p_updated_by INT,
    p_updated_at TIMESTAMPTZ,
    p_update_source TEXT,
    p_status_id INT,
    p_received_quantity INT,
    p_has_comments BOOLEAN,
    p_multiple_fulfillments BOOLEAN,
    p_archived_by VARCHAR,
    p_reason TEXT,
    p_role_id INT,
    p_user_id INT
)
RETURNS VOID AS $$
BEGIN
    -- Insert the line item into the archive table
    INSERT INTO archived_MRL_line_items (
        order_line_item_id,
        jcn,
        twcode,
        nomenclature,
        cog,
        fsc,
        niin,
        part_no,
        qty,
        ui,
        market_research_up,
        market_research_ep,
        avail_typ,
        request_date,
        rdd,
        pri,
        swlin,
        hull_or_shop,
        suggested_source,
        mfg_cage,
        apl,
        nha_equipment_system,
        nha_model,
        nha_serial,
        techmanual,
        dwg_pc,
        requestor_remarks,
        inquiry_status,
        created_by,
        created_at,
        updated_by,
        updated_at,
        update_source,
        status_id,
        received_quantity,
        has_comments,
        multiple_fulfillments,
        archived_by,
        archived_at,
        archive_reason
    )
    SELECT
        p_order_line_item_id,
        p_jcn,
        p_twcode,
        p_nomenclature,
        p_cog,
        p_fsc,
        p_niin,
        p_part_no,
        p_qty,
        p_ui,
        p_market_research_up,
        p_market_research_ep,
        p_avail_typ,
        p_request_date,
        p_rdd,
        p_pri,
        p_swlin,
        p_hull_or_shop,
        p_suggested_source,
        p_mfg_cage,
        p_apl,
        p_nha_equipment_system,
        p_nha_model,
        p_nha_serial,
        p_techmanual,
        p_dwg_pc,
        p_requestor_remarks,
        p_inquiry_status,
        p_created_by,
        p_created_at,
        p_updated_by,
        p_updated_at,
        p_update_source,
        p_status_id,
        p_received_quantity,
        p_has_comments,
        p_multiple_fulfillments,
        p_archived_by,
        CURRENT_TIMESTAMP,
        p_reason
    FROM MRL_line_items
    WHERE order_line_item_id = p_order_line_item_id;

    -- Delete the line item from the original table
    DELETE FROM MRL_line_items
    WHERE order_line_item_id = p_order_line_item_id;

    -- Insert into audit trail
    INSERT INTO audit_trail (
        order_line_item_id,
        action,
        changed_by,
        changed_at,
        details,
        update_source,
        role_id,
        user_id
    )
    VALUES (
        p_order_line_item_id,
        'Line Item Archived',
        p_archived_by,
        CURRENT_TIMESTAMP,
        p_reason,
        'Archive Operation',
        p_role_id,
        p_user_id
    );
END;
$$ LANGUAGE plpgsql;
